spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.unreleased.work/auth/realms/onelabs-realm/protocol/openid-connect/certs
    basic:
      enabled: false
  data:
    rest:
      return-body-on-create: true
      return-body-on-update: true
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: password
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    exchange:
#      name: allocation-exchange
#      key:  allocation
#    requested-heartbeat: 15s
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: allocation-exchange
#          group: allocation
#        output:
#          destination: allocation-exchange
#          group: allocation

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
eureka:
#  instance:
#    nonSecurePort: 80
#    hostname: localhost:8761
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  server:
    waitTimeInMsWhenSyncEmpty: 0
